---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: haproxy-openmanager-backend
  namespace: haproxy-openmanager
  labels:
    app: haproxy-openmanager
    component: backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: haproxy-openmanager-frontend
  namespace: haproxy-openmanager
  labels:
    app: haproxy-openmanager
    component: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: haproxy-openmanager-postgres
  namespace: haproxy-openmanager
  labels:
    app: haproxy-openmanager
    component: postgres
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: haproxy-openmanager-redis
  namespace: haproxy-openmanager
  labels:
    app: haproxy-openmanager
    component: redis

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: haproxy-openmanager-nginx
  namespace: haproxy-openmanager
  labels:
    app: haproxy-openmanager
    component: nginx 